import {NextResponse} from "next/server";
import {cachedSourceData,getCachedSourceData,saveSourceData} from "../source-cache";
export const dynamic="force-dynamic";
const BASE="https://environment.na.go.kr:444";const SCHEDULE=`${BASE}/cmmit/schl/cmitSchl/schlList.do?menuNo=2000048`;const LEGISLATION=`${BASE}/cmmit/lgsltpa/lgsltpa/ongoingList.do?menuNo=2000082`;
const clean=(value:string)=>value.replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g," ").trim();
const absolute=(value:string,page:string)=>{try{return new URL(value.replace(/&amp;/gi,"&"),page).toString()}catch{return page}};
async function getHtml(url:string){const response=await fetch(url,{headers:{Accept:"text/html","User-Agent":"GS-ENR-Monitor/1.0"},cache:"no-store"});if(!response.ok)throw new Error(`위원회 ${response.status}`);return response.text()}
async function readSchedule(){const html=await getHtml(SCHEDULE);const seen=new Set<string>();return [...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].flatMap((match,index)=>{const row=match[1];const text=clean(row);const date=text.match(/20\d{2}[.\/-]\d{1,2}[.\/-]\d{1,2}/)?.[0];if(!date)return[];const anchors=[...row.matchAll(/<a[^>]+(?:href|data-url)=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(a=>({url:absolute(a[1],SCHEDULE),label:clean(a[2])}));const title=anchors.find(a=>a.label.length>4&&!/미리보기|다운로드|첨부/.test(a.label))?.label||text.replace(date,"").replace(/미리보기|다운로드/g,"").trim();if(!title||seen.has(`${date}-${title}`))return[];seen.add(`${date}-${title}`);const preview=anchors.find(a=>/미리보기|view/i.test(a.label+a.url))?.url||anchors[0]?.url||SCHEDULE;const download=anchors.find(a=>/다운로드|download|fileDown/i.test(a.label+a.url))?.url||preview;return[{id:`schedule-${index}`,date,title,previewUrl:preview,downloadUrl:download}];}).slice(0,10)}
async function readLegislation(){const html=await getHtml(LEGISLATION);const seen=new Set<string>();return [...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].flatMap((match,index)=>{const row=match[1];const link=[...row.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(a=>({url:absolute(a[1],LEGISLATION),title:clean(a[2])})).find(a=>a.title.length>5);if(!link||seen.has(link.url))return[];seen.add(link.url);const text=clean(row);const dates=[...text.matchAll(/20\d{2}[.\/-]\d{1,2}[.\/-]\d{1,2}/g)].map(m=>m[0]);return[{id:`legislation-${index}`,title:link.title,period:dates.length>1?`${dates[0]} ~ ${dates[1]}`:dates[0]||"",url:link.url}];}).slice(0,10)}
export async function GET(request:Request){if(!new URL(request.url).searchParams.has("refresh")){const cached=await getCachedSourceData("environment-committee");if(cached)return NextResponse.json(cached,{headers:{"Cache-Control":"private, no-store"}});}try{const[schedules,legislation]=await Promise.all([readSchedule(),readLegislation()]);if(!schedules.length&&!legislation.length)throw new Error("위원회 목록을 확인하지 못했습니다.");return NextResponse.json(await saveSourceData("environment-committee",{schedules,legislation,sourceUrls:{schedule:SCHEDULE,legislation:LEGISLATION}}));}catch(error){const cached=await cachedSourceData("environment-committee",error);return cached?NextResponse.json(cached):NextResponse.json({error:error instanceof Error?error.message:"위원회 연결 실패"},{status:502});}}
